
/*
Conversion de Estructura hacia estructura M_MIGRACIONES7
Ultima modificacion: Banpro B_Migraciones2009
*/


USE [B_MIGRACIONES2010]
GO
/****** Objeto:  Table [dbo].[T_ESTILOM7]    Fecha de la secuencia de comandos: 11/20/2014 14:17:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[T_ESTILOM7](
	[BANCO] [char](4) NOT NULL,
	[CUENTA] [varchar](20) NOT NULL,
	[CEDULA] [varchar](10) NULL,
	[TIPO_PERSONA] [char](1) NULL,
	[NOMBRE_TITULAR] [varchar](100) NULL,
	[FECHA_NACIMIENTO] [smalldatetime] NULL,
	[TIPO_CUENTA] [tinyint] NULL,
	[TIPO_INSTRUMENTO] [tinyint] NULL,
	[TIPO_DEPOSITO] [tinyint] NULL,
	[TIPO_FIRMA] [char](1) NULL,
	[SALDO_ACTUAL] [numeric](18, 2) NULL,
	[DIRECCION] [varchar](500) NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF

INSERT INTO T_ESTILOM7 (BANCO,CUENTA,CEDULA,TIPO_PERSONA,NOMBRE_TITULAR,FECHA_NACIMIENTO,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,
SALDO_ACTUAL,DIRECCION)
select BANCO,CUENTA,CEDULA_TITULAR,TIPO_PERSONA,NOMBRE_TITULAR,FECHA_NACIMIENTO_TITULAR,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,SALDO_ACTUAL,DIRECCION from dbo.m_MIGRACIONES3

INSERT INTO T_ESTILOM7 (BANCO,CUENTA,CEDULA,TIPO_PERSONA,NOMBRE_TITULAR,FECHA_NACIMIENTO,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,
SALDO_ACTUAL,DIRECCION)
select BANCO, CUENTA, cedula_co_titular1,persona_co_titular1,nombre_co_titular1,fecha_nacimiento_co_titular1,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,SALDO_ACTUAL,DIRECCION
from dbo.m_MIGRACIONES3

INSERT INTO T_ESTILOM7 (BANCO,CUENTA,CEDULA,TIPO_PERSONA,NOMBRE_TITULAR,FECHA_NACIMIENTO,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,
SALDO_ACTUAL,DIRECCION)
select BANCO, CUENTA, cedula_co_titular2,persona_co_titular2,nombre_co_titular2,fecha_nacimiento_co_titular2,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,SALDO_ACTUAL,DIRECCION
from dbo.m_MIGRACIONES3

INSERT INTO T_ESTILOM7 (BANCO,CUENTA,CEDULA,TIPO_PERSONA,NOMBRE_TITULAR,FECHA_NACIMIENTO,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,
SALDO_ACTUAL,DIRECCION)
select BANCO, CUENTA, cedula_co_titular3,persona_co_titular3,nombre_co_titular3,fecha_nacimiento_co_titular3,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,SALDO_ACTUAL,DIRECCION
from dbo.m_MIGRACIONES3

INSERT INTO T_ESTILOM7 (BANCO,CUENTA,CEDULA,TIPO_PERSONA,NOMBRE_TITULAR,FECHA_NACIMIENTO,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,
SALDO_ACTUAL,DIRECCION)
select BANCO, CUENTA, cedula_co_titular4,persona_co_titular4,nombre_co_titular4,fecha_nacimiento_co_titular4,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,SALDO_ACTUAL,DIRECCION
from dbo.m_MIGRACIONES3

INSERT INTO T_ESTILOM7 (BANCO,CUENTA,CEDULA,TIPO_PERSONA,NOMBRE_TITULAR,FECHA_NACIMIENTO,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,
SALDO_ACTUAL,DIRECCION)
--persona_co_titular5,
select BANCO, CUENTA, cedula_co_titular5,'x',nombre_co_titular5,fecha_nacimiento_co_titular5,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,SALDO_ACTUAL,DIRECCION
from dbo.m_MIGRACIONES3


INSERT INTO T_ESTILOM7 (BANCO,CUENTA,CEDULA,TIPO_PERSONA,NOMBRE_TITULAR,FECHA_NACIMIENTO,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,
SALDO_ACTUAL,DIRECCION)
--persona_co_titular6,
select BANCO, CUENTA, cedula_co_titular6,'x',nombre_co_titular6,fecha_nacimiento_co_titular6,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,SALDO_ACTUAL,DIRECCION
from dbo.m_MIGRACIONES3


INSERT INTO T_ESTILOM7 (BANCO,CUENTA,CEDULA,TIPO_PERSONA,NOMBRE_TITULAR,FECHA_NACIMIENTO,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,
SALDO_ACTUAL,DIRECCION)
--persona_co_titular7
select BANCO, CUENTA, cedula_co_titular7,'x',nombre_co_titular7,fecha_nacimiento_co_titular7,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,SALDO_ACTUAL,DIRECCION
from dbo.m_migraciones3

INSERT INTO T_ESTILOM7 (BANCO,CUENTA,CEDULA,TIPO_PERSONA,NOMBRE_TITULAR,FECHA_NACIMIENTO,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,
SALDO_ACTUAL,DIRECCION)
--persona_co_titular8,
select BANCO, CUENTA, cedula_co_titular3,'x',nombre_co_titular8,fecha_nacimiento_co_titular8,TIPO_CUENTA,TIPO_INSTRUMENTO,TIPO_DEPOSITO,TIPO_FIRMA,SALDO_ACTUAL,DIRECCION
from dbo.m_migraciones3

SELECT * FROM DBO.T_ESTILOM7

DELETE FROM DBO.T_ESTILOM7
WHERE CEDULA IS NULL AND TIPO_PERSONA IS NULL AND FECHA_NACIMIENTO IS NULL


SELECT * FROM DBO.T_ESTILOM7

SELECT * FROM DBO.T_ESTILOM7 WHERE FECHA_NACIMIENTO IS NULL

DELETE FROM DBO.T_ESTILOM7
WHERE FECHA_NACIMIENTO IS NULL

(2317992 filas afectadas)

SELECT * FROM DBO.T_ESTILOM7 where cedula is null

DELETE FROM DBO.T_ESTILOM7
WHERE cedula IS NULL

(1271091 filas afectadas)